project:
  type: website
  output-dir: docs

website:
  title: "Arkadiusz Lipiecki"
  navbar:
    left:
      - cv.qmd
      - pubs.qmd
      - software.qmd
      - confs.qmd
  announcement: 
    icon: bi bi-globe-americas
    dismissable: false
    content: "From June 28 to July 1 you can find me in Montreal at the International Symposium on Forecasting"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true
