project:
  type: website
  output-dir: docs

website:
  title: "Arkadiusz Lipiecki"
  navbar:
    left:
      - cv.qmd
      - pubs.qmd
      - software.qmd
  #announcement: 
    #dismissable: false
    #content: "..."
    #type: primary
    #position: below-navbar

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: true
