---
title: "Publications"
---

## Working papers
- A. Lipiecki, R. Weron. *Foundation models for electricity price forecasting and battery arbitrage: Can they replace market-specific forecasting models?*. [arXiv.2609.00089](https://doi.org/10.48550/arXiv.2609.00089)
- P. Zaborowski, A. Lipiecki, F. Petropoulos, R.Weron. *Probabilistic forecasting via post-processing prediction errors: In- or out-of-sample?*. [arXiv:2608.10620](https://doi.org/10.48550/arXiv.2608.10620)
- A. Lipiecki, B. Uniejewski. *Isotonic Quantile Regression Averaging for uncertainty quantification of electricity price forecasts*. [arXiv.2507.15079](https://doi.org/10.48550/arXiv.2507.15079)

## Published papers

- B. Kamińska, B. Nowak, A. Lipiecki, K. Sznajd-Weron. *Competition between private and expressed opinions in binary choice: The α-EPO q-voter model*. **Physical Review E** 113(6), 064301 (2026). [10.1103/8w9t-jpvp](https://doi.org/10.1103/8w9t-jpvp)
- K. Maciejowska, A. Lipiecki, B. Uniejewski. *Statistical and economic evaluation of forecasts in electricity markets: Beyond RMSE and MAE*. **Energy Conversion and Management** 356, 121408 (2026). [10.1016/j.enconman.2026.121408](https://doi.org/10.1016/j.enconman.2026.121408)
- A. Lipiecki, K. Bilińska, N. Kourentzes, R. Weron. *Stealing accuracy: Predicting day-ahead electricity prices with temporal hierarchy forecasting (THieF)*. **International Journal of Forecasting** 42(4) (2026). [10.1016/j.ijforecast.2026.03.003](https://doi.org/10.1016/j.ijforecast.2026.03.003)
- A. Lipiecki, R. Weron. *PostForecasts.jl: A Julia package for probabilistic forecasting by postprocessing point predictions*. **SoftwareX** 31, 102200 (2025). [10.1016/j.softx.2025.102200](https://doi.org/10.1016/j.softx.2025.102200)
- A. Lipiecki, K. Sznajd-Weron. *Depolarizing power of anticonformity*. **Expert Systems with Applications** 285, 127879 (2025). [10.1016/j.eswa.2025.127879](https://doi.org/10.1016/j.eswa.2025.127879)
- A. Lipiecki, K. Sznajd-Weron. *When heterogeneity drives hysteresis: Anticonformity in the multistate q -voter model on networks*. **Physical Review E** 112(5), 054316 (2025). [10.1103/9f3r-fsrr](https://doi.org/10.1103/9f3r-fsrr)
- A. Lipiecki, B. Uniejewski, R. Weron. *Postprocessing of point predictions for probabilistic forecasting of day-ahead electricity prices: The benefits of using isotonic distributional regression*. **Energy Economics** 139, 107934 (2024). [10.1016/j.eneco.2024.107934](https://doi.org/10.1016/j.eneco.2024.107934)
- A. Lipiecki. *Strategic Promotional Campaigns for Sustainable Behaviors: Maximizing Influence in Competitive Complex Contagions*. **Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)** 14834 LNCS (2024). [10.1007/978-3-031-63759-9_8](https://doi.org/10.1007/978-3-031-63759-9_8)
- M. Doniec, A. Lipiecki, K. Sznajd-Weron. *Consensus, Polarization and Hysteresis in the Three-State Noisy q-Voter Model with Bounded Confidence*. **Entropy** 24(7), 983 (2022). [10.3390/e24070983](https://doi.org/10.3390/e24070983)
- A. Lipiecki, K. Sznajd-Weron. *Polarization in the three-state q-voter model with anticonformity and bounded confidence*. **Chaos, Solitons and Fractals** 165, 112809 (2022). [10.1016/j.chaos.2022.112809](https://doi.org/10.1016/j.chaos.2022.112809)
- A. Abramiuk-Szurlej, A. Lipiecki, J. Pawłowski, K. Sznajd-Weron. *Discontinuous phase transitions in the q-voter model with generalized anticonformity on random graphs*. **Scientific Reports** 11(1), 17719 (2021). [10.1038/s41598-021-97155-0](https://doi.org/10.1038/s41598-021-97155-0)
